run:
  timeout: 5m
  tests: true     # inclure les tests dans le lint

linters:
  enable:
    - govet          # vérifications officielles du compilateur
    - errcheck       # vérifier les erreurs non gérées
    - staticcheck    # linter avancé pour erreurs et mauvaises pratiques
    - gosimple       # simplifications possibles
    - unused         # code inutilisé
    - deadcode       # code mort
    - gofmt          # vérifie que le code est bien formaté
    - goimports      # vérifie les imports inutilisés ou manquants
    - gocyclo        # cyclomatic complexity (complexité cyclomatique)
    - structcheck    # vérifie les champs inutilisés dans les structs
  disable:
    - golint         # souvent trop verbeux et déprécié

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-use-default: false

linters-settings:
  gofmt:
    simplify: true  # active simplification automatique lors du lint

  gocyclo:
    min-complexity: 15  # avertit si complexité > 15 (à ajuster selon projet)

  errcheck:
    # Ignorer quelques fonctions courantes si besoin
    ignore: 
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Println